### ISSUE TITLE
打不开包里的RdpTest.exe

### ISSUE THREAD

**Issue by liudaolunboluo** [xunki/RemoteDesktopManage#10]
是不是因为我系统是win8.1的原因？

**Comment by xunki** [comment]
是不是在压缩包里面打开的？如果是，请先解压到文件夹。
如果不是，请描述下错误提示？
或检查下 .NET Framework 版本，理论上 `461` 以上都能直接打开的。

**Comment by liudaolunboluo** [comment]
点了之后没反应并且也没报错

**Comment by liudaolunboluo** [comment]
点了之后没反应并且也没报错

**Comment by xunki** [comment]
抱歉，这我就不太清楚了。。无能为力。

**Comment by liudaolunboluo** [comment]
安装了 .NET Framework然后重启电脑之后解决，建议能够在readme中说明必须要 .NET Framework或者能再打开的时候检测本机上是否有 .NET Framework

**Comment by xunki** [comment]
按讲 .NET Framework 缺失，Windows 会有相应提示的，不过我之前在其他项目上也遇到过一些PC上没有提示，目前还不知道是啥原因。

完善文档的确是非常有必要的，感谢你的反馈！
