### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by simonln** [xunki/RemoteDesktopManage#11]
1.配置好全局配置后，新增配置的时候能够默认使用全局配置（不然添加全局配置的意义在哪？）
2.增加全屏功能。远程连接到远端主机后，主机的显示只在局部控件里，缩放后看起来别扭。

**Comment by xunki** [comment]
1、此功能目前就是这样实现的，并且可用，起码在我本地是如此 `尝试下载最新的 Release 程序试下？`

2、全屏功能之前是有的，后来我把去掉了，因为对我个人实际体验并不好。

全屏功能很简单，调用 `AxMsRdpClient` 的 `API` 就好了，但全屏后的效果是在空间里面分辨率多大，全屏后的分辨率就是多大，如果想调整分辨率必须重新登录。

我最早的实现是用当前显示器的分辨率，虽然全屏是没啥问题的，但在页签模式下是需要缩放或增加滚动条，用起来非常不舒服。

后来我使用控件可显示区域的分辨率，这样就会造成全屏时分辨率还是控件定义的分辨率，想要重置则断开此连接，重新开一个连接设置好全屏的分辨率后再登录，这就很鸡肋了。

后来，我在页签下使用也挺顺手，主要是方便在多个远程界面中切换，所以一直保持这种状态。

**当然，我一直按照自己的习惯来折腾，所以还望继续交流，找到更佳的使用方式**

现在，我对自己这个工具不满的地方主要还是头部占用了太多的空间，浪费了显示区域，不过是基于
`Winforms-Modernui` 这个 UI 框架做的，最近忙于工作与学习，所以没精力再探索这个了。

**再次感谢你能给出建议**

**Comment by simonln** [comment]
1、关于第一个问题，我下载了最新版的Release运行了，还是不行。我第一次跑的时候是用源码编完跑的，review了一下源码，新增节点配置部分没有看到有显式调用GlobalConfig类。
2.我在MainForm.ConnectRemoteHost函数里调用了
```C#
rdpClient.FullScreen = true
```
全屏功能正常，分辨率也正常（和使用系统自带的远程桌面连接一样）。我的主机是*windows10专业版（1803）*，远端主机*Windows Server2012R2 Standard* 和 *Windows7 SP1*

**Comment by xunki** [comment]
1、新增节点，在 Load 界面的时候，默认加载了 GlobalConfig 的配置，请查看代码：
https://github.com/xunki/RemoteDesktopManage/blob/f695786db285a17042d58da2afa17a57f0c36e89/RemoteDesktopManage/RemoteHostForm.cs#L33-L35

2、至于第二个问题，我试的效果如下，跟我之前描述的现象是一样的，除非指定 Width 和 Height 为当前屏幕的分辨率，至于是否是环境问题我暂时无法得证。
![IMG_20190705_142554](https://user-images.githubusercontent.com/3375799/60702301-25543400-9f31-11e9-85bc-6be253ca0538.jpg)

**不过，既然你改代码就太棒了，请按照你的习惯随意改造，也欢迎提 Pull Request，更希望能看到实际应用的效果**

**Comment by simonln** [comment]
十分感谢您的回复！
1.第一个问题，我发现是咱们相互对全局配置理解有偏差。我指的全局配置是包含用户名和密码。
2.第二个问题我上午仔细review了一下自己的更改，发现是我错了。具体现象和你第一个回复描述的一样。我再去翻翻文档看看有什么更优雅的方式可以实现全屏这个功能。

**Comment by xunki** [comment]
1、第一个问题果然是问题，我发现我的全局配置里面有用户名和密码，维护了新增时不带出，这是一个问题。

而且，我目前的 `全局配置` 实际用处不大，也就方便新增，其实应该做成子项继承全局的逻辑并可以重写的逻辑，但目前没这么做。。

**假如有时间的话，我会优化这块的**

**Comment by xunki** [comment]
1、此问题已确认是BUG并在 486f79e02b91674f1328cb189ec86e79b7160398 中解决了

**其实全局配置应该做成子项继承全局的逻辑并可以允许修改的逻辑，不过以后再说咯**
