### ISSUE TITLE
咨询项目

### ISSUE THREAD

**Issue by jiaqiyu543** [xunki/RemoteDesktopManage#12]
目前我这边有个项目，想要咨询作者像MSTSC是否可以写进主板里  我想自己设计一个盒子不用主机只通过自己的盒子接受信号，传送到显示屏

**Comment by xunki** [comment]
不太理解写到主板里是什么意思，烧录单片机还是？

1、盒子是Windows主机，配置接收远程访问，然后通过IP直接连就好。
2、盒子不是主机，只是做一个转发，在盒子上装个 Proxy 或自己写一个，转发一下数据就好了 (现在大多路由器都能设置这个功能 `端口映射` )
3、盒子是Linux主机，这......   还是用 Putty、MobaXterm 等工具连吧，至于想远程访问桌面系统，在 Linux 装个 VNC 或者其他桌面系统即可
