### ISSUE TITLE
大佬,怎么设置大小,不能全屏

### ISSUE THREAD

**Issue by xman55555** [xunki/RemoteDesktopManage#13]
貌似不能全屏,没有自带的全屏,而且共享盘是怎么用的?

**Comment by adinet** [comment]
看源码, 本来是没做全屏的, 可以自己改一下, 应该不太复杂
[RemoteDesktopManage/MainForm.cs](https://github.com/xunki/RemoteDesktopManage/blob/master/RemoteDesktopManage/MainForm.cs)
line: 104 - 110
`
var rdpClient = new AxMsRdpClient9NotSafeForScripting
 {
    Dock = DockStyle.None,
    Width = page.Width,
    Height = page.Height
};
page.Controls.Add(rdpClient);
`

**Comment by xunki** [comment]
可以参考项目中注释的代码，修改远程桌面为本机的全屏分辨率
https://github.com/xunki/RemoteDesktopManage/blob/486f79e02b91674f1328cb189ec86e79b7160398/RemoteDesktopManage/MainForm.cs#L147-L151

全屏的话，只需一行代码设置 `运行过程中也可以设置`
```
rdpClient.FullScreen = true;
```

共享的磁盘启用后在远程桌面里就能看到映射，如下图所示
![设置](https://user-images.githubusercontent.com/3375799/62264122-49803380-b451-11e9-81cd-a2cffa5c8bc1.png)
![效果](https://user-images.githubusercontent.com/3375799/62264118-471dd980-b451-11e9-9d6d-68ecd3fadcd8.png)
