### ISSUE TITLE
试了一下，无法使用，空白页

### ISSUE THREAD

**Issue by YuanDdQiao** [xunki/RemoteDesktopManage#14]
点击连接后，显示正在连接，然后就空白了

**Comment by xunki** [comment]
试试 MSTSC 能不能正常连上...

**Comment by YuanDdQiao** [comment]
能。

**Comment by Hooper-He** [comment]
文件dll文件都没有？

**Comment by YuanDdQiao** [comment]
啥提示都没有。白板，我就下载你提供的 RemoteDesktopManage.zip 啊。

**Comment by xunki** [comment]
今天我同事也遇上了这个问题，不过用 `管理员权限` 运行程序，就可以了。
请你也试试看。

可以尝试以下解决办法：

解决方法（一）：右键 -> 以管理员权限运行

![image](https://user-images.githubusercontent.com/3375799/64965191-20b3e080-d8cf-11e9-9940-d6fe50d11908.png)

解决方法（二）：右键 -> 属性 -> 兼容性 -> 勾上 `以管理员身份运行此程序` -> 再直接打开程序

![image](https://user-images.githubusercontent.com/3375799/64965296-53f66f80-d8cf-11e9-8f88-8437a02a9f59.png)


**PS. 我已经在程序中加了一个  `管理员权限` 的清单申明 (图标会带上小盾牌)，如果运行程序弹出以下提示，请按照 `解决方法（二）` 或配置组策略允许程序提权** 

![image](https://user-images.githubusercontent.com/3375799/64965381-6ec8e400-d8cf-11e9-9c7f-78d212a86a93.png)

**Comment by sxyandapp** [comment]
~我遇到了同样的问题，用管理员权限运行也不行，单独使用系统里的远程桌面是没问题的，环境是win10x64~
远程ip输错了，能使用
