### ISSUE TITLE
提示错误：从服务器返回了一个参照

### ISSUE THREAD

**Issue by fly869** [xunki/RemoteDesktopManage#16]
![image](https://user-images.githubusercontent.com/15951171/70959467-5d060100-20b7-11ea-97c2-a6d4e2e1c188.png)

**Comment by chaorenna** [comment]
我也是同样的问题

**Comment by fly869** [comment]
@chaorenna 在属性->兼容性那里勾选一下以管理员运行就可以解决了，我的是这样解决的

**Comment by xunki** [comment]
解决方法请参考 #14
