### ISSUE TITLE
你好，我拉取了源码，想用VS2019重新编译，但提示好多错误，而且我直接下载你编译好的，在win10无法打开

### ISSUE THREAD

**Issue by hzdlive** [xunki/RemoteDesktopManage#17]

**Comment by xunki** [comment]
1、编译错误需要看报错内容，一般是 ActiveX 加载不了导致的，重新引用一下就好了
2、Win10 可能需要以管理员权限启动，请参考 #16

**Comment by hzdlive** [comment]
按你说方法，现在程序能打开了，有个冒昧请求：能否添加上同时打开几个主机时，实现几台主机键鼠同步控制的功能呢？

**Comment by xunki** [comment]
并不可以，我这个只是对 MSTSC 的封装，真正的 RDP 协议没有研究过。

**Comment by hzdlive** [comment]
remotedesktopmanager.cn
哦，我以为能实现这样的功能呢？
这个商业软件太贵了。

**Comment by hzdlive** [comment]
> 并不可以，我这个只是对 MSTSC 的封装，真正的 RDP 协议没有研究过。

好像没有设置分辨率的地方吧？

**Comment by xunki** [comment]
> 好像没有设置分辨率的地方吧？

设置宽和高就行
https://github.com/xunki/RemoteDesktopManage/blob/f856580d054938dadca65702ef12d18a9162a936/RemoteDesktopManage/MainForm.cs#L104-L109
