### ISSUE TITLE
仅启动程序报错“打开远程程序失败”

### ISSUE THREAD

**Issue by lonelysh** [xunki/RemoteDesktopManage#2]
仅启动程序 powershell.exe -command "stop-process -name xxxx"

打开远程程序失败
remoteAppResultNotInWhitelist

**Comment by xunki** [comment]
RemoteApp程序不在RD会话主机服务器的允许列表中，需要在服务端配置哦！

程序调用错误描述：https://docs.microsoft.com/zh-cn/windows/desktop/TermServ/imstscaxevents-onremoteprogramresult

解决办法：https://jingyan.baidu.com/article/6b182309502fc4ba58e1590c.html

**Comment by xunki** [comment]
解决办法：http://blog.51cto.com/llydmissile/1286934

最近在另一台机器上配置了这个功能，可以参考下这个资料。记得安装角色功能 `远程主机服务` `远程主机授权`
