### ISSUE TITLE
为何必须要用管理员启动？

### ISSUE THREAD

**Issue by Outlanderhong** [xunki/RemoteDesktopManage#20]
今天用了用这个工具，发现必须要管理员启动，才能运行？这是为何呢？

**Comment by lucheng12138** [comment]
管理员权限吧

**Comment by xunki** [comment]
部分电脑不以管理员权限运行会导致 mstsc 无法连接，所以直接在程序里面强制申明了必须以管理员权限启动。

**Comment by VShawn** [comment]
从 gitee 过来的，发现gitee上全是项目的 fork.
---

请问 mstsc 在什么情况下需要管理员权限？我在开发过程中没有遇到过，但不知道有没有用户会踩到这个坑。这个是我的项目：https://github.com/VShawn/PRemoteM ，欢迎交流。

**Comment by xunki** [comment]
> ## 从 gitee 过来的，发现gitee上全是项目的 fork.
> 请问 mstsc 在什么情况下需要管理员权限？我在开发过程中没有遇到过，但不知道有没有用户会踩到这个坑。这个是我的项目：https://github.com/VShawn/PRemoteM ，欢迎交流。
 
@VShawn 由别人反馈的，具体原因没细究，只是上网找了最简单的解决方案。
看了你的项目，非常不错，说起来有些惭愧，这个项目我已经很久没有维护了。

**Comment by VShawn** [comment]
原来如此，我暂时没有收到用户反馈，可能是某些公司电脑被IT设置了组策略使MSTSC要求提升权限。
---
我的项目也是bug一堆，疲于修复。
