### ISSUE TITLE
远程程序无法启动

### ISSUE THREAD

**Issue by VShawn** [xunki/RemoteDesktopManage#21]
按readme上添加了一个calc作为远程程序进行测试，但无法打开该远程程序，配置与提示如下。

![image](https://user-images.githubusercontent.com/10143738/104087100-5042e500-5298-11eb-82da-56d4e668d3e6.png)

![image](https://user-images.githubusercontent.com/10143738/104087112-63ee4b80-5298-11eb-9ec5-086a2d7be823.png)

**Comment by xunki** [comment]
解决方法请参考 #2

**Comment by VShawn** [comment]
已使用 [RemoteApp Tool](http://www.kimknight.net/remoteapptool) 解决设置问题。
