### ISSUE TITLE
大佬死否考虑加入软件启动密码？

### ISSUE THREAD

**Issue by nomoneynolife** [xunki/RemoteDesktopManage#23]
当添加多个节点后，其他人使用我的电脑数据泄露问题。即便是有人拷贝走了，也打不开。

如果软件被人逆向，强制跳过密码验证，是否可以

**Comment by nomoneynolife** [comment]
另外目前密码等敏感信息也是明码保存在config.的文件中

**Comment by xunki** [comment]
仅依赖本地加密意义不大，别人反编译项目源码自然知道是如何加密的了，开源代码进行混淆意义也不大。
所以一开始就不考虑此功能呢！

当然，源码在这，想怎么改就咋改吧。
