### ISSUE TITLE
似乎本地磁盘在远程系统中访问不到

### ISSUE THREAD

**Issue by ming300** [xunki/RemoteDesktopManage#3]
请问还没有支持吗？正常使用windows的msts是ok的。

**Comment by xunki** [comment]
嗯，目前只共享了剪切板，未支持挂载本地资源，会考虑加上挂载磁盘的配置的。不过至于完成时间嘛~~~

**Comment by xunki** [comment]
目前直接共享所有本地磁盘 (偷个懒)，暂时满足需求。

可以下载最新的 [RemoteDesktopManage](https://github.com/wang9563/RemoteDesktopManage/releases/tag/1.3)  试试
