### ISSUE TITLE
看到您已经解决了“连接远程时共享本地磁盘”问题，能否在源码中提供成品打包好的.exe文件。

### ISSUE THREAD

**Issue by ming300** [xunki/RemoteDesktopManage#4]
本地没有开发环境，没法编译呀。谢谢。

**Comment by xunki** [comment]
下载地址：[RemoteDesktopManage.zip](https://github.com/wang9563/RemoteDesktopManage/releases/download/1.3/RemoteDesktopManage.zip)

虽然有些偷懒，不过我的确重新编译并上传到 1.3 的 Release 中，可以通过此链接来下载程序，看看是否满足你的需求。

**Comment by ming300** [comment]
谢谢，很神奇，本地磁盘的盘符C盘没有出现在远程桌面中，其他盘符正常。基本够用。

**Comment by xunki** [comment]
Duplicate of #3
