### ISSUE TITLE
建议增加多个设置项

### ISSUE THREAD

**Issue by wangbf19740612** [xunki/RemoteDesktopManage#5]
例如配置远程连接参数/console等，以及设定启用剪切板、驱动器等等，建议参考rdcman的功能和设置，很喜欢这个工具，希望继续更新下去
rdcman下载地址：
https://www.microsoft.com/en-us/download/details.aspx?id=44989

**Comment by xunki** [comment]
感谢支持与建议，最近在考虑优化这些设置选项，也看了一下rdcman，它的设置选项几乎涵盖了官方MSTSC工具的所有参数，但如果我也同样照搬过来是否有意义呢？这样会把设置搞的有些繁琐，我更倾向于最简单的配置，目前我只准备加上以下配置项：

* 是否共享剪切板
* 选择性共享本地磁盘
* ~~提供全局参数设置（子项可单独配置）~~
* 提供默认参数设置，新增是自动带出，可单独配置 (子项不继承全局设置，担心界面按钮过多造成混淆)

如果确实需要其它的一些设置，请说明下使用场景，我不介意加上那些非常实用的功能（我貌似也就用个远程而已，捂脸）

代码已调整，请下载最新的 [release1.4 ](https://github.com/wang9563/RemoteDesktopManage/releases/download/1.4/RemoteDesktopManage.zip) 版本尝试看看。

**Comment by wangbf19740612** [comment]
/console这个参数在我们使用远程桌面维护服务器的时候是非常重要的一个参数，/console 模式等同于本地终端显示器登录，/console不会去占用非/console远程桌面。远程桌面允许两个正常连接和一个控制台/console方式连接，并且正常连接和/console连接的桌面操作不能相互看见。
综上所述，希望能够增加该选项，谢谢
再次感谢提供这么好的工具，这事目前国内远程桌面管理类工具中我个人感觉最好的！！

**Comment by xunki** [comment]
刚刚看了一下这个功能相关的文档并测试了一下，并没有任何效果，后来发现了这篇文章 [https://support.microsoft.com/en-us/help/947723/changes-to-remote-administration-in-windows-server-2008](https://support.microsoft.com/en-us/help/947723/changes-to-remote-administration-in-windows-server-2008) 

貌似在 Windows Server 2003 上才可以使用（我这边暂时没有可测试的服务器），并且在 Windows Server 的后续版本都不再需要 /console ，上述文章里面提及到问题可以参考一下，按照你所描述的场景，我觉得即使没有这个功能也没多大影响，或许您想有更多的远程桌面连接数，但这个可以通过 Windows 设置来增加最大远程连接数。

**Comment by wangbf19740612** [comment]
/console最大的用处是使用控制台模式登陆，而不是重新启动一个进程，可能是我得表达意思有误，汗颜......
在服务器上例如有运行的程序，不加 /console参数登录后是看不到当前运行程序的，必须切换一下用户才可以，很容易造成运维过程中重复运行程序，不知道这样说您是否能够理解，^_^
我感觉这个参数是必须要加上的，可以解决很大的痛点.....
你说的那个文档是有误的，亲测2008r2也需要这个参数......所以建议设置成可选项，再次感谢

**Comment by xunki** [comment]
抱歉，没有用过此功能，没啥概念，上网搜索到的也基本是基于 Windwos Server 2003 的。
也可以 [点此链接](http://wpa.qq.com/msgrd?v=3&uin=269314358&site=qq&menu=yes) 与我详细沟通，让我Get这个新技能。
