### ISSUE TITLE
空的父节点无法修改名称，也无法删除

### ISSUE THREAD

**Issue by lgjy143** [xunki/RemoteDesktopManage#6]
![image](https://user-images.githubusercontent.com/7710059/49680673-312e6380-fad2-11e8-950b-a875a34087a4.png)
父节点，远程，无法修改名称，也无法删除，修改得连接数据库操作有点麻烦

**Comment by xunki** [comment]
我一直都是添加个子节点，然后把父节点删除的（很少进行父节点的修改）。。。不过这样操作的确麻烦，会考虑进行优化。

**Comment by xunki** [comment]
在分组名(父节点)上右键可以进行编辑、删除操作了！
请下载 [目前最新版程序](https://github.com/wang9563/RemoteDesktopManage/releases/download/1.4/RemoteDesktopManage.zip) 试试看。
