### ISSUE TITLE
增加mstsc /admin参数选择

### ISSUE THREAD

**Issue by wangbf19740612** [xunki/RemoteDesktopManage#8]
维护中这个参数经常使用，还望能够增加该参数设置，谢谢！

**Comment by xunki** [comment]
这个参数貌似与 /console 类似，因为我这边环境切入远程时都会提示选择需要进入的远程桌面，/console 和  /admin 都没啥效果。。`可能是我用的 Mstsc ActiveX 控件版本比较高`

也没法测试，所以没打算加上。
如果有需要，你可以 fork 按需修改，并在你的环境中测试，当然功能完成之后，欢迎提交 Pull Request ，一起完善这个工具。

**Comment by xunki** [comment]
此建议已与 @wangbf19740612  沟通并解决，参考提交 2c473f6e090f2715340c8be943812305bb0e74e5 ，已编译并替换了最新版本的 [Release](https://github.com/wang9563/RemoteDesktopManage/releases/download/1.4/RemoteDesktopManage.zip)

**功能描述**
* 当使用 `/console` (低版本)  或 `/admin` 是默认会连接到会话0，这样维护时可以将带图形化界面的程序都放在会话0，避免出现多个会话时不知道程序出现在哪个会话中。
* 当用户通过 `/console` 连接到会话0，如果已有其他用户先连接到会话0，会将其他用户踢出。
* 从目前测试来看功能仅在 `Windows Server 2003` 中有效，详细描述请参考 [此处](https://support.microsoft.com/zh-cn/help/947723/changes-to-remote-administration-in-windows-server-2008)
