### ISSUE TITLE
能否添加关机操作

### ISSUE THREAD

**Issue by chenyingcong1** [xunki/RemoteDesktopManage#9]
能否添加关机操作

**Comment by xunki** [comment]
这个需求是用在什么场景下呢？
我们远程的其他主机一般是基本不会关机的服务器，基本上没有关机的情况，顶多只是重启，而且这个操作也是远程上服务器后，直接操作的。

当然如果要实现的话，可以考虑远程调用 `shutdown` 尝试一下，但感觉没有必要做这个功能。

**Comment by xunki** [comment]
不活跃的话题
